### ISSUE TITLE
Add question to faq

### ISSUE THREAD

**Issue by Varunram** [jjenzz/musicoin-frontend#66]
Let's add "How do I get verified" to the FAQ section. Way too many people asking the same stuff :(

**Comment by jjenzz** [comment]
> Let's add "How do I get verified" to the FAQ section. Way too many people asking the same stuff :(

What is this question in reference to? Is this about how they get an access code during sign up?

**Comment by Varunram** [comment]
Oh, this? This is with reference to how musicians can get verified on our site. I added a banner on the sign up page, so I'll close this for now.
